# Generated by Django 2.0.7 on 2019-07-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190718_2002'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='relacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes'),
            preserve_default=False,
        ),
    ]
