# Generated by Django 2.0.7 on 2019-07-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productos_relacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='relacion',
        ),
    ]
