# Generated by Django 2.0.7 on 2019-07-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personas',
            new_name='Clientes',
        ),
    ]
